dependencies:
  build:
    - ruby:2.4.5

build_targets:
  - name: default
    commands:
      - gem install bundler
      - bundle install 
      - bundle exec rake
  - name: release
    commands:
      - echo "RELEASE"

ci:
  builds:
    - name: build_gem
      build_targets: default
